spring.application.name=spring-login-jpa

spring.datasource.url=jdbc:postgresql://loclahost:5432/login_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=admin
spring.security.user.password=admin123
